### ISSUE TITLE
Update Minimal schemes for Komodo v9 and add to repository

### ISSUE THREAD

**Issue by we3geeks** [we3geeks/komodo-color-schemes#3]

**Comment by Defman21** [comment]
Minimal schemes?

**Comment by we3geeks** [comment]
I have a pair of basic "schemes" that I use as the starting point for all of my scheme work: the dark version is just white on black, and the light version is just black on white. I've gone through and cleared (almost) all of the colors, so that I have a minimal, clean slate to work with...

They aren't schemes I would ever actually use for editing but I have found them much easier to start with when I start working on a new scheme, because I know that there aren't odd colors tucked away somewhere in the scheme from whatever I started with. I call them Minimal-Light and Minimal-Dark.
