### ISSUE TITLE
Line-height?

### ISSUE THREAD

**Issue by Defman21** [we3geeks/komodo-color-schemes#6]
Are you sure it should be 0?

**Comment by we3geeks** [comment]
@Defman21 Can you elaborate on your question? I'm not sure what you are asking...

**Comment by Defman21** [comment]
![that](http://i.imgur.com/MWE13Xl.png)

**Comment by we3geeks** [comment]
Ah, thanks. Line spacing... got it. 

Yes, the font family I use in Komodo ([David Jonathon Ross's Input](http://input.fontbureau.com/)) and which is specified in these schemes has default line spacing of 1.2x (but can be configured differently when downloaded) which I think works well, so I've left spacing in Komodo at 0.
